# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'phonetic_mark_tool_ui.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1379, 714)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../Basic_Dashboard_UI_fix_option_machine_tools-512.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pb_mark_full_file = QtWidgets.QPushButton(self.centralwidget)
        self.pb_mark_full_file.setGeometry(QtCore.QRect(80, 450, 491, 41))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pb_mark_full_file.setFont(font)
        self.pb_mark_full_file.setObjectName("pb_mark_full_file")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(810, 20, 301, 31))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.pb_wrong_lab = QtWidgets.QPushButton(self.centralwidget)
        self.pb_wrong_lab.setGeometry(QtCore.QRect(740, 150, 441, 31))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pb_wrong_lab.setFont(font)
        self.pb_wrong_lab.setObjectName("pb_wrong_lab")
        self.pb_phone_analysis = QtWidgets.QPushButton(self.centralwidget)
        self.pb_phone_analysis.setGeometry(QtCore.QRect(720, 400, 261, 41))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pb_phone_analysis.setFont(font)
        self.pb_phone_analysis.setObjectName("pb_phone_analysis")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(80, 110, 561, 31))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setInputMethodHints(QtCore.Qt.ImhFormattedNumbersOnly)
        self.label_3.setObjectName("label_3")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(50, 60, 601, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(43, 70, 20, 571))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(50, 270, 601, 31))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_4.setGeometry(QtCore.QRect(640, 70, 20, 571))
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(80, 520, 381, 21))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setInputMethodHints(QtCore.Qt.ImhFormattedNumbersOnly)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(80, 550, 441, 21))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setInputMethodHints(QtCore.Qt.ImhFormattedNumbersOnly)
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(70, 230, 291, 31))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setInputMethodHints(QtCore.Qt.ImhFormattedNumbersOnly)
        self.label_13.setObjectName("label_13")
        self.line_5 = QtWidgets.QFrame(self.centralwidget)
        self.line_5.setGeometry(QtCore.QRect(50, 630, 601, 31))
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(730, 350, 111, 31))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setInputMethodHints(QtCore.Qt.ImhFormattedNumbersOnly)
        self.label_7.setObjectName("label_7")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(730, 370, 271, 31))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setInputMethodHints(QtCore.Qt.ImhFormattedNumbersOnly)
        self.label_9.setObjectName("label_9")
        self.tb_wrong_lab = QtWidgets.QTextBrowser(self.centralwidget)
        self.tb_wrong_lab.setGeometry(QtCore.QRect(720, 220, 441, 101))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.tb_wrong_lab.setFont(font)
        self.tb_wrong_lab.setObjectName("tb_wrong_lab")
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(720, 190, 251, 31))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setInputMethodHints(QtCore.Qt.ImhFormattedNumbersOnly)
        self.label_16.setObjectName("label_16")
        self.label_18 = QtWidgets.QLabel(self.centralwidget)
        self.label_18.setGeometry(QtCore.QRect(720, 440, 441, 31))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setInputMethodHints(QtCore.Qt.ImhFormattedNumbersOnly)
        self.label_18.setObjectName("label_18")
        self.line_6 = QtWidgets.QFrame(self.centralwidget)
        self.line_6.setGeometry(QtCore.QRect(690, 60, 561, 20))
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.line_7 = QtWidgets.QFrame(self.centralwidget)
        self.line_7.setGeometry(QtCore.QRect(680, 70, 20, 581))
        self.line_7.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.line_8 = QtWidgets.QFrame(self.centralwidget)
        self.line_8.setGeometry(QtCore.QRect(690, 640, 561, 20))
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.line_9 = QtWidgets.QFrame(self.centralwidget)
        self.line_9.setGeometry(QtCore.QRect(1240, 70, 20, 581))
        self.line_9.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.pb_big5_utf8 = QtWidgets.QPushButton(self.centralwidget)
        self.pb_big5_utf8.setGeometry(QtCore.QRect(90, 180, 521, 41))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pb_big5_utf8.setFont(font)
        self.pb_big5_utf8.setObjectName("pb_big5_utf8")
        self.label_19 = QtWidgets.QLabel(self.centralwidget)
        self.label_19.setGeometry(QtCore.QRect(360, 230, 291, 31))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setInputMethodHints(QtCore.Qt.ImhFormattedNumbersOnly)
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.centralwidget)
        self.label_20.setGeometry(QtCore.QRect(80, 370, 281, 31))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_20.setFont(font)
        self.label_20.setInputMethodHints(QtCore.Qt.ImhFormattedNumbersOnly)
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.centralwidget)
        self.label_21.setGeometry(QtCore.QRect(80, 400, 321, 31))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_21.setFont(font)
        self.label_21.setInputMethodHints(QtCore.Qt.ImhFormattedNumbersOnly)
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.centralwidget)
        self.label_22.setGeometry(QtCore.QRect(720, 120, 261, 21))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_22.setFont(font)
        self.label_22.setInputMethodHints(QtCore.Qt.ImhFormattedNumbersOnly)
        self.label_22.setObjectName("label_22")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(990, 120, 231, 21))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setInputMethodHints(QtCore.Qt.ImhFormattedNumbersOnly)
        self.label_10.setObjectName("label_10")
        self.pb_mark_mono_file = QtWidgets.QPushButton(self.centralwidget)
        self.pb_mark_mono_file.setGeometry(QtCore.QRect(750, 550, 441, 31))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pb_mark_mono_file.setFont(font)
        self.pb_mark_mono_file.setObjectName("pb_mark_mono_file")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(720, 590, 381, 21))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setInputMethodHints(QtCore.Qt.ImhFormattedNumbersOnly)
        self.label_15.setObjectName("label_15")
        self.label_23 = QtWidgets.QLabel(self.centralwidget)
        self.label_23.setGeometry(QtCore.QRect(720, 620, 441, 21))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_23.setFont(font)
        self.label_23.setInputMethodHints(QtCore.Qt.ImhFormattedNumbersOnly)
        self.label_23.setObjectName("label_23")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(70, 80, 71, 31))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setInputMethodHints(QtCore.Qt.ImhFormattedNumbersOnly)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(70, 310, 101, 31))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setInputMethodHints(QtCore.Qt.ImhFormattedNumbersOnly)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(710, 80, 281, 31))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setInputMethodHints(QtCore.Qt.ImhFormattedNumbersOnly)
        self.label_6.setObjectName("label_6")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(710, 330, 101, 31))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setInputMethodHints(QtCore.Qt.ImhFormattedNumbersOnly)
        self.label_8.setObjectName("label_8")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(710, 490, 281, 31))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setInputMethodHints(QtCore.Qt.ImhFormattedNumbersOnly)
        self.label_14.setObjectName("label_14")
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(720, 520, 141, 31))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setInputMethodHints(QtCore.Qt.ImhFormattedNumbersOnly)
        self.label_17.setObjectName("label_17")
        self.pb_sentences_analysis = QtWidgets.QPushButton(self.centralwidget)
        self.pb_sentences_analysis.setGeometry(QtCore.QRect(990, 400, 231, 41))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pb_sentences_analysis.setFont(font)
        self.pb_sentences_analysis.setObjectName("pb_sentences_analysis")
        self.label_24 = QtWidgets.QLabel(self.centralwidget)
        self.label_24.setGeometry(QtCore.QRect(720, 470, 441, 21))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_24.setFont(font)
        self.label_24.setInputMethodHints(QtCore.Qt.ImhFormattedNumbersOnly)
        self.label_24.setObjectName("label_24")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(200, 20, 158, 41))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_25 = QtWidgets.QLabel(self.centralwidget)
        self.label_25.setGeometry(QtCore.QRect(80, 150, 241, 21))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_25.setFont(font)
        self.label_25.setInputMethodHints(QtCore.Qt.ImhFormattedNumbersOnly)
        self.label_25.setObjectName("label_25")
        self.label_26 = QtWidgets.QLabel(self.centralwidget)
        self.label_26.setGeometry(QtCore.QRect(80, 340, 261, 31))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_26.setFont(font)
        self.label_26.setInputMethodHints(QtCore.Qt.ImhFormattedNumbersOnly)
        self.label_26.setObjectName("label_26")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(310, 120, 131, 61))
        self.widget.setObjectName("widget")
        self.rb_big5 = QtWidgets.QRadioButton(self.widget)
        self.rb_big5.setGeometry(QtCore.QRect(10, 30, 83, 20))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.rb_big5.setFont(font)
        self.rb_big5.setChecked(True)
        self.rb_big5.setObjectName("rb_big5")
        self.rb_utf8 = QtWidgets.QRadioButton(self.widget)
        self.rb_utf8.setGeometry(QtCore.QRect(70, 30, 61, 21))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.rb_utf8.setFont(font)
        self.rb_utf8.setObjectName("rb_utf8")
        self.widget_2 = QtWidgets.QWidget(self.centralwidget)
        self.widget_2.setGeometry(QtCore.QRect(330, 320, 131, 51))
        self.widget_2.setObjectName("widget_2")
        self.rb_utf8_2 = QtWidgets.QRadioButton(self.widget_2)
        self.rb_utf8_2.setGeometry(QtCore.QRect(70, 20, 61, 31))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.rb_utf8_2.setFont(font)
        self.rb_utf8_2.setObjectName("rb_utf8_2")
        self.rb_big5_2 = QtWidgets.QRadioButton(self.widget_2)
        self.rb_big5_2.setGeometry(QtCore.QRect(10, 20, 61, 31))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.rb_big5_2.setFont(font)
        self.rb_big5_2.setCheckable(True)
        self.rb_big5_2.setChecked(True)
        self.rb_big5_2.setObjectName("rb_big5_2")
        self.widget_3 = QtWidgets.QWidget(self.centralwidget)
        self.widget_3.setGeometry(QtCore.QRect(830, 330, 131, 61))
        self.widget_3.setObjectName("widget_3")
        self.rb_utf8_3 = QtWidgets.QRadioButton(self.widget_3)
        self.rb_utf8_3.setGeometry(QtCore.QRect(70, 20, 61, 31))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.rb_utf8_3.setFont(font)
        self.rb_utf8_3.setObjectName("rb_utf8_3")
        self.rb_big5_3 = QtWidgets.QRadioButton(self.widget_3)
        self.rb_big5_3.setGeometry(QtCore.QRect(10, 20, 61, 31))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.rb_big5_3.setFont(font)
        self.rb_big5_3.setCheckable(True)
        self.rb_big5_3.setChecked(True)
        self.rb_big5_3.setObjectName("rb_big5_3")
        self.label_27 = QtWidgets.QLabel(self.centralwidget)
        self.label_27.setGeometry(QtCore.QRect(950, 350, 271, 31))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_27.setFont(font)
        self.label_27.setInputMethodHints(QtCore.Qt.ImhFormattedNumbersOnly)
        self.label_27.setObjectName("label_27")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1379, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "注音標記工具"))
        self.pb_mark_full_file.setText(_translate("MainWindow", "產生注音檔"))
        self.label_2.setText(_translate("MainWindow", "錄音後-時長檢查與分析、標記注音"))
        self.pb_wrong_lab.setText(_translate("MainWindow", "挑出時長標記錯誤之lab"))
        self.pb_phone_analysis.setText(_translate("MainWindow", "產生音節時長分析檔"))
        self.label_3.setText(_translate("MainWindow", "在內建corpus資料夾中放corpus.txt，格式為一句一列"))
        self.label_11.setText(_translate("MainWindow", "※多句注音檔位於: mark.txt"))
        self.label_12.setText(_translate("MainWindow", "※單句注音多檔位於: sentence_mark/"))
        self.label_13.setText(_translate("MainWindow", "※分句(big5)位於: corpus/big5/"))
        self.label_7.setText(_translate("MainWindow", "a.在corpus/"))
        self.label_9.setText(_translate("MainWindow", "b.txt檔名格式: a流水號.txt"))
        self.label_16.setText(_translate("MainWindow", "錯誤lab檔案路徑及錯誤原因:"))
        self.label_18.setText(_translate("MainWindow", "※音節時長分析檔位於: phonetic_analysis.txt"))
        self.pb_big5_utf8.setText(_translate("MainWindow", "產生分句檔"))
        self.label_19.setText(_translate("MainWindow", "※分句(utf8)位於: corpus/utf8/"))
        self.label_20.setText(_translate("MainWindow", "b.在label/half_full/中放lab檔案"))
        self.label_21.setText(_translate("MainWindow", "c.lab檔名格式: Somefile_流水號.lab"))
        self.label_22.setText(_translate("MainWindow", "a.在label/mono/中放lab檔案"))
        self.label_10.setText(_translate("MainWindow", "b.lab檔名格式: a流水號.lab"))
        self.pb_mark_mono_file.setText(_translate("MainWindow", "產生注音檔"))
        self.label_15.setText(_translate("MainWindow", "※多句注音檔位於: mark.txt"))
        self.label_23.setText(_translate("MainWindow", "※單句注音多檔位於: sentence_mark/"))
        self.label_4.setText(_translate("MainWindow", "1.分句:"))
        self.label_5.setText(_translate("MainWindow", "2.產注音:"))
        self.label_6.setText(_translate("MainWindow", "1.時長檢查:"))
        self.label_8.setText(_translate("MainWindow", "2.時長分析:"))
        self.label_14.setText(_translate("MainWindow", "3.產注音:"))
        self.label_17.setText(_translate("MainWindow", "須完成前2步驟"))
        self.pb_sentences_analysis.setText(_translate("MainWindow", "產生單句時長分析檔"))
        self.label_24.setText(_translate("MainWindow", "※單句時長分析檔位於: sentences_analysis.txt"))
        self.label.setText(_translate("MainWindow", "錄音前-標記注音"))
        self.label_25.setText(_translate("MainWindow", "選擇corpus.txt的編碼格式:"))
        self.label_26.setText(_translate("MainWindow", "a.選擇與哪個資料夾的txt對應:"))
        self.rb_big5.setText(_translate("MainWindow", "big5"))
        self.rb_utf8.setText(_translate("MainWindow", "utf8"))
        self.rb_utf8_2.setText(_translate("MainWindow", "utf8"))
        self.rb_big5_2.setText(_translate("MainWindow", "big5"))
        self.rb_utf8_3.setText(_translate("MainWindow", "utf8"))
        self.rb_big5_3.setText(_translate("MainWindow", "big5"))
        self.label_27.setText(_translate("MainWindow", "澤一放txt檔"))

