# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'phonetic_mark_tool_ui.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1331, 696)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../Basic_Dashboard_UI_fix_option_machine_tools-512.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pb_mark_full_file = QtWidgets.QPushButton(self.centralwidget)
        self.pb_mark_full_file.setGeometry(QtCore.QRect(80, 370, 491, 41))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pb_mark_full_file.setFont(font)
        self.pb_mark_full_file.setObjectName("pb_mark_full_file")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(240, 20, 161, 31))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(810, 20, 301, 31))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.pb_wrong_lab = QtWidgets.QPushButton(self.centralwidget)
        self.pb_wrong_lab.setGeometry(QtCore.QRect(740, 220, 441, 41))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pb_wrong_lab.setFont(font)
        self.pb_wrong_lab.setObjectName("pb_wrong_lab")
        self.pb_phone_analysis = QtWidgets.QPushButton(self.centralwidget)
        self.pb_phone_analysis.setGeometry(QtCore.QRect(740, 540, 441, 41))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pb_phone_analysis.setFont(font)
        self.pb_phone_analysis.setObjectName("pb_phone_analysis")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(80, 90, 561, 31))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setInputMethodHints(QtCore.Qt.ImhFormattedNumbersOnly)
        self.label_3.setObjectName("label_3")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(50, 60, 581, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(43, 70, 20, 561))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(50, 250, 581, 31))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_4.setGeometry(QtCore.QRect(620, 70, 20, 571))
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(80, 430, 381, 21))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setInputMethodHints(QtCore.Qt.ImhFormattedNumbersOnly)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(80, 460, 441, 21))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setInputMethodHints(QtCore.Qt.ImhFormattedNumbersOnly)
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(80, 180, 351, 31))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setInputMethodHints(QtCore.Qt.ImhFormattedNumbersOnly)
        self.label_13.setObjectName("label_13")
        self.line_5 = QtWidgets.QFrame(self.centralwidget)
        self.line_5.setGeometry(QtCore.QRect(50, 620, 581, 31))
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(740, 80, 541, 31))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setInputMethodHints(QtCore.Qt.ImhFormattedNumbersOnly)
        self.label_7.setObjectName("label_7")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(740, 120, 451, 21))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setInputMethodHints(QtCore.Qt.ImhFormattedNumbersOnly)
        self.label_9.setObjectName("label_9")
        self.tb_wrong_lab = QtWidgets.QTextBrowser(self.centralwidget)
        self.tb_wrong_lab.setGeometry(QtCore.QRect(740, 300, 441, 101))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.tb_wrong_lab.setFont(font)
        self.tb_wrong_lab.setObjectName("tb_wrong_lab")
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(740, 270, 251, 31))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setInputMethodHints(QtCore.Qt.ImhFormattedNumbersOnly)
        self.label_16.setObjectName("label_16")
        self.label_18 = QtWidgets.QLabel(self.centralwidget)
        self.label_18.setGeometry(QtCore.QRect(750, 600, 441, 21))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setInputMethodHints(QtCore.Qt.ImhFormattedNumbersOnly)
        self.label_18.setObjectName("label_18")
        self.line_6 = QtWidgets.QFrame(self.centralwidget)
        self.line_6.setGeometry(QtCore.QRect(690, 60, 531, 20))
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.line_7 = QtWidgets.QFrame(self.centralwidget)
        self.line_7.setGeometry(QtCore.QRect(680, 70, 20, 571))
        self.line_7.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.line_8 = QtWidgets.QFrame(self.centralwidget)
        self.line_8.setGeometry(QtCore.QRect(690, 630, 531, 20))
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.line_9 = QtWidgets.QFrame(self.centralwidget)
        self.line_9.setGeometry(QtCore.QRect(1210, 70, 20, 571))
        self.line_9.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.pb_big5_utf8 = QtWidgets.QPushButton(self.centralwidget)
        self.pb_big5_utf8.setGeometry(QtCore.QRect(80, 130, 491, 41))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pb_big5_utf8.setFont(font)
        self.pb_big5_utf8.setObjectName("pb_big5_utf8")
        self.label_19 = QtWidgets.QLabel(self.centralwidget)
        self.label_19.setGeometry(QtCore.QRect(80, 210, 351, 31))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setInputMethodHints(QtCore.Qt.ImhFormattedNumbersOnly)
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.centralwidget)
        self.label_20.setGeometry(QtCore.QRect(80, 280, 611, 31))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_20.setFont(font)
        self.label_20.setInputMethodHints(QtCore.Qt.ImhFormattedNumbersOnly)
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.centralwidget)
        self.label_21.setGeometry(QtCore.QRect(80, 320, 611, 31))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_21.setFont(font)
        self.label_21.setInputMethodHints(QtCore.Qt.ImhFormattedNumbersOnly)
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.centralwidget)
        self.label_22.setGeometry(QtCore.QRect(740, 150, 611, 31))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_22.setFont(font)
        self.label_22.setInputMethodHints(QtCore.Qt.ImhFormattedNumbersOnly)
        self.label_22.setObjectName("label_22")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(740, 190, 451, 21))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setInputMethodHints(QtCore.Qt.ImhFormattedNumbersOnly)
        self.label_10.setObjectName("label_10")
        self.pb_mark_mono_file = QtWidgets.QPushButton(self.centralwidget)
        self.pb_mark_mono_file.setGeometry(QtCore.QRect(740, 420, 441, 41))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pb_mark_mono_file.setFont(font)
        self.pb_mark_mono_file.setObjectName("pb_mark_mono_file")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(740, 470, 381, 21))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setInputMethodHints(QtCore.Qt.ImhFormattedNumbersOnly)
        self.label_15.setObjectName("label_15")
        self.label_23 = QtWidgets.QLabel(self.centralwidget)
        self.label_23.setGeometry(QtCore.QRect(740, 500, 441, 21))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_23.setFont(font)
        self.label_23.setInputMethodHints(QtCore.Qt.ImhFormattedNumbersOnly)
        self.label_23.setObjectName("label_23")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1331, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "注音標記工具"))
        self.pb_mark_full_file.setText(_translate("MainWindow", "產生兩種注音檔:多句注音檔、單句注音多檔(utf8)"))
        self.label.setText(_translate("MainWindow", "錄音前-標記注音"))
        self.label_2.setText(_translate("MainWindow", "錄音後-標記注音、時長檢查與分析"))
        self.pb_wrong_lab.setText(_translate("MainWindow", "挑出時長標記錯誤之lab"))
        self.pb_phone_analysis.setText(_translate("MainWindow", "產生音節時長分析檔"))
        self.label_3.setText(_translate("MainWindow", "在corpus資料夾裡面放corpus.txt檔案(big5)，格式為一行一句"))
        self.label_11.setText(_translate("MainWindow", "※多句注音檔產生路徑: mark.txt"))
        self.label_12.setText(_translate("MainWindow", "※單句注音多檔產生路徑: sentence_mark/"))
        self.label_13.setText(_translate("MainWindow", "※big編碼檔案產生路徑: corpus/big5/"))
        self.label_7.setText(_translate("MainWindow", "1.在corpus/big5/路徑下放big5編碼的txt檔案"))
        self.label_9.setText(_translate("MainWindow", "2.txt檔名格式: a流水號.txt"))
        self.label_16.setText(_translate("MainWindow", "錯誤lab檔案路徑及錯誤原因:"))
        self.label_18.setText(_translate("MainWindow", "※音節時長分析檔產生路徑: phonetic_analysis.txt"))
        self.pb_big5_utf8.setText(_translate("MainWindow", "產生兩種分句檔: big5編碼、utf8編碼"))
        self.label_19.setText(_translate("MainWindow", "※utf8編碼檔案產生路徑: corpus/utf8/"))
        self.label_20.setText(_translate("MainWindow", "1.在label/half_full/資料夾裡面放lab檔案"))
        self.label_21.setText(_translate("MainWindow", "2.檔名格式: Somefile_流水號.lab"))
        self.label_22.setText(_translate("MainWindow", "3.label/mono/資料夾裡面lab檔案"))
        self.label_10.setText(_translate("MainWindow", "4.lab檔名格式: a流水號.lab"))
        self.pb_mark_mono_file.setText(_translate("MainWindow", "產生兩種注音檔:多句注音檔、單句注音多檔(utf8)"))
        self.label_15.setText(_translate("MainWindow", "※多句注音檔產生路徑: mark.txt"))
        self.label_23.setText(_translate("MainWindow", "※單句注音多檔產生路徑: sentence_mark/"))

